version: '3'

services:
  api:
    build: .
    command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    container_name: temp_service
    volumes:
      - .:/temp_service
    ports:
      - "8000:8000"
