version: '3'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    container_name: project_w_server
    volumes:
      - .:/project_w_server
    ports:
      - "8000:8000"
